/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as KeralaRouteImport } from './routes/kerala'
import { Route as InternationalPackagesRouteImport } from './routes/international-packages'
import { Route as GuestStoriesRouteImport } from './routes/guest-stories'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DomesticPackagesRouteImport } from './routes/domestic-packages'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabsRouteImport } from './routes/cabs'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TripIdRouteImport } from './routes/trip.$id'
import { Route as GuestStoriesSlugRouteImport } from './routes/guest-stories.$slug'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AgencyDashboardRouteImport } from './routes/agency/dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminCmsVehiclesRouteImport } from './routes/admin/cms/vehicles'
import { Route as AdminCmsStoriesRouteImport } from './routes/admin/cms/stories'
import { Route as AdminCmsPackagesRouteImport } from './routes/admin/cms/packages'
import { Route as AdminCmsFeedbackRouteImport } from './routes/admin/cms/feedback'
import { Route as AdminCmsFaqsRouteImport } from './routes/admin/cms/faqs'
import { Route as AdminCmsDestinationsRouteImport } from './routes/admin/cms/destinations'
import { Route as AdminCmsBlogRouteImport } from './routes/admin/cms/blog'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const KeralaRoute = KeralaRouteImport.update({
  id: '/kerala',
  path: '/kerala',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalPackagesRoute = InternationalPackagesRouteImport.update({
  id: '/international-packages',
  path: '/international-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestStoriesRoute = GuestStoriesRouteImport.update({
  id: '/guest-stories',
  path: '/guest-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticPackagesRoute = DomesticPackagesRouteImport.update({
  id: '/domestic-packages',
  path: '/domestic-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabsRoute = CabsRouteImport.update({
  id: '/cabs',
  path: '/cabs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestStoriesSlugRoute = GuestStoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuestStoriesRoute,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsVehiclesRoute = AdminCmsVehiclesRouteImport.update({
  id: '/admin/cms/vehicles',
  path: '/admin/cms/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsStoriesRoute = AdminCmsStoriesRouteImport.update({
  id: '/admin/cms/stories',
  path: '/admin/cms/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPackagesRoute = AdminCmsPackagesRouteImport.update({
  id: '/admin/cms/packages',
  path: '/admin/cms/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsFeedbackRoute = AdminCmsFeedbackRouteImport.update({
  id: '/admin/cms/feedback',
  path: '/admin/cms/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsFaqsRoute = AdminCmsFaqsRouteImport.update({
  id: '/admin/cms/faqs',
  path: '/admin/cms/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsDestinationsRoute = AdminCmsDestinationsRouteImport.update({
  id: '/admin/cms/destinations',
  path: '/admin/cms/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsBlogRoute = AdminCmsBlogRouteImport.update({
  id: '/admin/cms/blog',
  path: '/admin/cms/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/domestic-packages': typeof DomesticPackagesRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/guest-stories': typeof GuestStoriesRouteWithChildren
  '/international-packages': typeof InternationalPackagesRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guest-stories/$slug': typeof GuestStoriesSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/blog': typeof AdminCmsBlogRoute
  '/admin/cms/destinations': typeof AdminCmsDestinationsRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/feedback': typeof AdminCmsFeedbackRoute
  '/admin/cms/packages': typeof AdminCmsPackagesRoute
  '/admin/cms/stories': typeof AdminCmsStoriesRoute
  '/admin/cms/vehicles': typeof AdminCmsVehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/domestic-packages': typeof DomesticPackagesRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/guest-stories': typeof GuestStoriesRouteWithChildren
  '/international-packages': typeof InternationalPackagesRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guest-stories/$slug': typeof GuestStoriesSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cms/blog': typeof AdminCmsBlogRoute
  '/admin/cms/destinations': typeof AdminCmsDestinationsRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/feedback': typeof AdminCmsFeedbackRoute
  '/admin/cms/packages': typeof AdminCmsPackagesRoute
  '/admin/cms/stories': typeof AdminCmsStoriesRoute
  '/admin/cms/vehicles': typeof AdminCmsVehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/domestic-packages': typeof DomesticPackagesRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/guest-stories': typeof GuestStoriesRouteWithChildren
  '/international-packages': typeof InternationalPackagesRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/guest-stories/$slug': typeof GuestStoriesSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/blog': typeof AdminCmsBlogRoute
  '/admin/cms/destinations': typeof AdminCmsDestinationsRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/feedback': typeof AdminCmsFeedbackRoute
  '/admin/cms/packages': typeof AdminCmsPackagesRoute
  '/admin/cms/stories': typeof AdminCmsStoriesRoute
  '/admin/cms/vehicles': typeof AdminCmsVehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/domestic-packages'
    | '/feedback'
    | '/generate'
    | '/guest-stories'
    | '/international-packages'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/agency/dashboard'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/guest-stories/$slug'
    | '/trip/$id'
    | '/admin/'
    | '/admin/cms/blog'
    | '/admin/cms/destinations'
    | '/admin/cms/faqs'
    | '/admin/cms/feedback'
    | '/admin/cms/packages'
    | '/admin/cms/stories'
    | '/admin/cms/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/domestic-packages'
    | '/feedback'
    | '/generate'
    | '/guest-stories'
    | '/international-packages'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/agency/dashboard'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/guest-stories/$slug'
    | '/trip/$id'
    | '/admin'
    | '/admin/cms/blog'
    | '/admin/cms/destinations'
    | '/admin/cms/faqs'
    | '/admin/cms/feedback'
    | '/admin/cms/packages'
    | '/admin/cms/stories'
    | '/admin/cms/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/domestic-packages'
    | '/feedback'
    | '/generate'
    | '/guest-stories'
    | '/international-packages'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/agency/dashboard'
    | '/blog/$slug'
    | '/destinations/$slug'
    | '/guest-stories/$slug'
    | '/trip/$id'
    | '/admin/'
    | '/admin/cms/blog'
    | '/admin/cms/destinations'
    | '/admin/cms/faqs'
    | '/admin/cms/feedback'
    | '/admin/cms/packages'
    | '/admin/cms/stories'
    | '/admin/cms/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CabsRoute: typeof CabsRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  DomesticPackagesRoute: typeof DomesticPackagesRoute
  FeedbackRoute: typeof FeedbackRoute
  GenerateRoute: typeof GenerateRoute
  GuestStoriesRoute: typeof GuestStoriesRouteWithChildren
  InternationalPackagesRoute: typeof InternationalPackagesRoute
  KeralaRoute: typeof KeralaRoute
  PackagesRoute: typeof PackagesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  VisaRoute: typeof VisaRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  TripIdRoute: typeof TripIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsBlogRoute: typeof AdminCmsBlogRoute
  AdminCmsDestinationsRoute: typeof AdminCmsDestinationsRoute
  AdminCmsFaqsRoute: typeof AdminCmsFaqsRoute
  AdminCmsFeedbackRoute: typeof AdminCmsFeedbackRoute
  AdminCmsPackagesRoute: typeof AdminCmsPackagesRoute
  AdminCmsStoriesRoute: typeof AdminCmsStoriesRoute
  AdminCmsVehiclesRoute: typeof AdminCmsVehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kerala': {
      id: '/kerala'
      path: '/kerala'
      fullPath: '/kerala'
      preLoaderRoute: typeof KeralaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-packages': {
      id: '/international-packages'
      path: '/international-packages'
      fullPath: '/international-packages'
      preLoaderRoute: typeof InternationalPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-stories': {
      id: '/guest-stories'
      path: '/guest-stories'
      fullPath: '/guest-stories'
      preLoaderRoute: typeof GuestStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic-packages': {
      id: '/domestic-packages'
      path: '/domestic-packages'
      fullPath: '/domestic-packages'
      preLoaderRoute: typeof DomesticPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabs': {
      id: '/cabs'
      path: '/cabs'
      fullPath: '/cabs'
      preLoaderRoute: typeof CabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-stories/$slug': {
      id: '/guest-stories/$slug'
      path: '/$slug'
      fullPath: '/guest-stories/$slug'
      preLoaderRoute: typeof GuestStoriesSlugRouteImport
      parentRoute: typeof GuestStoriesRoute
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/vehicles': {
      id: '/admin/cms/vehicles'
      path: '/admin/cms/vehicles'
      fullPath: '/admin/cms/vehicles'
      preLoaderRoute: typeof AdminCmsVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/stories': {
      id: '/admin/cms/stories'
      path: '/admin/cms/stories'
      fullPath: '/admin/cms/stories'
      preLoaderRoute: typeof AdminCmsStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/packages': {
      id: '/admin/cms/packages'
      path: '/admin/cms/packages'
      fullPath: '/admin/cms/packages'
      preLoaderRoute: typeof AdminCmsPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/feedback': {
      id: '/admin/cms/feedback'
      path: '/admin/cms/feedback'
      fullPath: '/admin/cms/feedback'
      preLoaderRoute: typeof AdminCmsFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/faqs': {
      id: '/admin/cms/faqs'
      path: '/admin/cms/faqs'
      fullPath: '/admin/cms/faqs'
      preLoaderRoute: typeof AdminCmsFaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/destinations': {
      id: '/admin/cms/destinations'
      path: '/admin/cms/destinations'
      fullPath: '/admin/cms/destinations'
      preLoaderRoute: typeof AdminCmsDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/blog': {
      id: '/admin/cms/blog'
      path: '/admin/cms/blog'
      fullPath: '/admin/cms/blog'
      preLoaderRoute: typeof AdminCmsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

interface GuestStoriesRouteChildren {
  GuestStoriesSlugRoute: typeof GuestStoriesSlugRoute
}

const GuestStoriesRouteChildren: GuestStoriesRouteChildren = {
  GuestStoriesSlugRoute: GuestStoriesSlugRoute,
}

const GuestStoriesRouteWithChildren = GuestStoriesRoute._addFileChildren(
  GuestStoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CabsRoute: CabsRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  DomesticPackagesRoute: DomesticPackagesRoute,
  FeedbackRoute: FeedbackRoute,
  GenerateRoute: GenerateRoute,
  GuestStoriesRoute: GuestStoriesRouteWithChildren,
  InternationalPackagesRoute: InternationalPackagesRoute,
  KeralaRoute: KeralaRoute,
  PackagesRoute: PackagesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  VisaRoute: VisaRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  TripIdRoute: TripIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsBlogRoute: AdminCmsBlogRoute,
  AdminCmsDestinationsRoute: AdminCmsDestinationsRoute,
  AdminCmsFaqsRoute: AdminCmsFaqsRoute,
  AdminCmsFeedbackRoute: AdminCmsFeedbackRoute,
  AdminCmsPackagesRoute: AdminCmsPackagesRoute,
  AdminCmsStoriesRoute: AdminCmsStoriesRoute,
  AdminCmsVehiclesRoute: AdminCmsVehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
