/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as KeralaRouteImport } from './routes/kerala'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CabsRouteImport } from './routes/cabs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TripIdRouteImport } from './routes/trip.$id'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as AgencyDashboardRouteImport } from './routes/agency/dashboard'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const KeralaRoute = KeralaRouteImport.update({
  id: '/kerala',
  path: '/kerala',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CabsRoute = CabsRouteImport.update({
  id: '/cabs',
  path: '/cabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripIdRoute = TripIdRouteImport.update({
  id: '/trip/$id',
  path: '/trip/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DestinationsRoute,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/agency/dashboard',
  path: '/agency/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cabs': typeof CabsRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRouteWithChildren
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/kerala': typeof KeralaRoute
  '/packages': typeof PackagesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stories': typeof StoriesRoute
  '/visa': typeof VisaRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/trip/$id': typeof TripIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/feedback'
    | '/generate'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/agency/dashboard'
    | '/destinations/$slug'
    | '/trip/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/feedback'
    | '/generate'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/agency/dashboard'
    | '/destinations/$slug'
    | '/trip/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cabs'
    | '/contact'
    | '/destinations'
    | '/feedback'
    | '/generate'
    | '/kerala'
    | '/packages'
    | '/sitemap.xml'
    | '/stories'
    | '/visa'
    | '/agency/dashboard'
    | '/destinations/$slug'
    | '/trip/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CabsRoute: typeof CabsRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRouteWithChildren
  FeedbackRoute: typeof FeedbackRoute
  GenerateRoute: typeof GenerateRoute
  KeralaRoute: typeof KeralaRoute
  PackagesRoute: typeof PackagesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoriesRoute: typeof StoriesRoute
  VisaRoute: typeof VisaRoute
  AgencyDashboardRoute: typeof AgencyDashboardRoute
  TripIdRoute: typeof TripIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kerala': {
      id: '/kerala'
      path: '/kerala'
      fullPath: '/kerala'
      preLoaderRoute: typeof KeralaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabs': {
      id: '/cabs'
      path: '/cabs'
      fullPath: '/cabs'
      preLoaderRoute: typeof CabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/$id': {
      id: '/trip/$id'
      path: '/trip/$id'
      fullPath: '/trip/$id'
      preLoaderRoute: typeof TripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof DestinationsRoute
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/agency/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DestinationsRouteChildren {
  DestinationsSlugRoute: typeof DestinationsSlugRoute
}

const DestinationsRouteChildren: DestinationsRouteChildren = {
  DestinationsSlugRoute: DestinationsSlugRoute,
}

const DestinationsRouteWithChildren = DestinationsRoute._addFileChildren(
  DestinationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CabsRoute: CabsRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRouteWithChildren,
  FeedbackRoute: FeedbackRoute,
  GenerateRoute: GenerateRoute,
  KeralaRoute: KeralaRoute,
  PackagesRoute: PackagesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoriesRoute: StoriesRoute,
  VisaRoute: VisaRoute,
  AgencyDashboardRoute: AgencyDashboardRoute,
  TripIdRoute: TripIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
